site_name: Sigma Docs
theme:
  name: material

nav:
  - Tour: 
      - Introduction:  tour/introduction.md
      - Login: tour/login.md
      - Profile: tour/profile.md
      - CMS dashboard: tour/cms-dashboard
      - Grids: tour/grids.md
  - Display:
      - Display: displays/displays.md
      - Display Setting: displays/display-setting.md
      - Groups: displays/groups.md
      - File/Layout Assignment: displays/file-layout.md
  - Layouts:
      - Introduction: layout/layout-intro.md
      - Layout Designer: layout/layout-designers.md
      - Regions: layout/Regions.md
      - Widgets: layout/widgets.md
      - Library search: layout/library-search.md
      - Layout Timeline: layout/layout-timeline.md
      - Interactive Actions: layout/interactive-actions.md
      - Templates: layout/templates.md
      - Campaigns: layout/campaign.md
      - Overlay Layouts: layout/overlay-layouts.md
      - Interrupt Layouts: layout/interrupt-layout.md
  - Media:
      - Introduction: media/introduction.md
      - Library: media/library.md
      - Tidy Library: media/tidy-library.md
      - Resizing Images: media/resizingImages.md
      - Playlists: media/playlists.md
      - Data Sets: media/dataset.md
      - Menu Boards: media/menuboards.md
      - Dashboard Service: media/dashboard-service.md
  - Modules:
      - Modules: module/modules.md
      - Agenda: module/agenda.md
      - Audio: module/audio.md
      - Calender: module/calender.md
      - Chart: module/chart.md
      - Clock: module/clock.md
      - Countdown: module/countdown.md
      - Currencies: module/currency.md
      - Dashboard: module/dashboard.md
      - Dataset Ticker: module/dataset-ticker.md
      - Dataset View: module/dataset-view.md
      - Embedded: module/embedded.md
      - Flash: module/flash.md
      - Google Traffic: module/google-traffic.md
      - HLS: module/HLS.md
      - HTML package: module/html-Package.md
      - Image: module/image.md
      - Local Video: module/local-video.md
      - Menu Boards: module/menu-boards.md
      - Notification: module/notification.md
      - PDF: module/PDF.md
      - Powerpoint: module/powerPoint.md
      - Shell Command: module/shell-command.md
      - Spacer: module/spacer.md
      - Stocks: module/stocks.md
      - Sub Playlist: module/sub-playlist.md
      - Text: module/text.md
      - Ticker: module/ticker.md
      - Twitter: module/twitter.md
      - Twitter Metro: module/twitter-metro.md
      - Videos: module/video.md
      - Video In: module/video-in.md
      - Weather: module/weather.md
      - Webpage: module/webpage.md
      - Word Clock: module/worldClock.md
  - Scheduling:
      - Introduction: scheduling/introduction.md
      - Schedule: scheduling/schedule.md
      - Events: scheduling/events.md
      - Geo Scheduling: scheduling/geo-scheduling.md
      - Dayparting: scheduling/dayparting.md
      - Schedule Now: scheduling/schedule-now.md
  - Troubleshooting:
      - Troubleshooting: troubleshooting/troubleshooting.md

markdown_extensions:
  - tables



# //https://xibosignage.com/manual/en/layouts -- layout dekhi ko document ya bata banaune //display samma ko doc chai - https://doc.sigma-ds.com/layout/introduction/